### ISSUE TITLE
Embed mschart in Excel file

### ISSUE THREAD

**Issue by 11rchitwood** [ardata-fr/mschart#71]
Is it possible to embed an mschart in an Excel file?

**Comment by davidgohel** [comment]
The first paragraph of the CRAN page says: "Create native charts for 'Microsoft PowerPoint' and 'Microsoft Word' documents. " It means it can't produce PDF, XLSX, TXT, DAT... It can only produce Word and PowerPoint. 

Do you think I should write it so that user are not confused? I found detailed list that could be used to list all non supported output: https://en.wikipedia.org/wiki/List_of_filename_extensions_(A%E2%80%93E). Would you be ok to let me write the full list of non-supported outputs? I foolishly assumed that readers would understand that if the list of supported formats was A and B, it meant "not C", "not D", "not E".

**Comment by 11rchitwood** [comment]
No, I think it's clear as is. If you've gotten this question a lot before, I'd be happy to add this to [the FAQ chapter of the officeverse book](https://ardata-fr.github.io/officeverse/faq.html).

I apologize for making an issue. I would have rather reached out in some other channel since this was a question not a bug report.

I would be interested in collaborating or even trying on my own to make it possible to embed an mschart in Excel, since I don't see a non-Java R way to do this. Is that within the scope of the officeverse banner?

Finally, thanks for your work and other collabators' on this great suite of packages.

**Comment by davidgohel** [comment]
I do get a lot of questions about things that are already explained in the documentation. There is also a search engine in the doc. So writing things in documentation does not help to decrease burden generated by Q asked by people that don't read the doc :)

It's not possible to let you PR in the book, you may note it, sources are not available. 

What would be the FAQ for that? 

*"Is is possible to write MSchart is Excel? - No"?*

It's not a frequent question. I also think users should understand that if possible to output to PPTX and DOCX, it does mean that it's not possible to generate an XLSX file or a PDF file. 

> I would be interested in collaborating or even trying on my own to make it possible to embed an mschart in Excel, since I don't see a non-Java R way to do this. Is that within the scope of the officeverse banner?

No, but feel free to rewrite everything, this is open source!
